FROM node:20-alpine

RUN apk add --no-cache python3 make g++ sqlite git

WORKDIR /app
RUN chown -R node:node /app
USER node

COPY --chown=node:node package*.json ./
RUN npm install

COPY --chown=node:node . .

EXPOSE 3000
CMD ["npm", "run", "dev"]
